server {
    listen 8080;
    listen 9001;
    server_name localhost test_server;
    root /home/houabell/webserv/www;
    index index.html;
    client_max_body_size 10M;

    # 1. Default location
    location / {
        # This will look for /tmp/www/index.html
        root /home/houabell/webserv/www;
    }

    # 2. Images location
    location /images {
        # If someone asks for /images/cat.jpg, it looks in /tmp/pictures/cat.jpg
        root /home/houabell/webserv/pictures;
    }

    # 3. Autoindex test location
    location /downloads {
        root /home/houabell/webserv/downloads;
        autoindex on;
    }
}
