server {
    listen 8080;
    server_name localhost;
    root /var/www;

    location / {
        limit_except GET POST {
            deny all;
        }
    }

    location /admin {
        limit_except INVALID {
            deny all;
        }
    }
}
