server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10m;
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 500 /errors/500.html;

    # serves static files
    location / {
        root www/static;
        index index.html;
        autoindex off;
        limit_except GET {
            deny all;
        }
    }

    # autoindex test
    location /images {
        root www;
        autoindex on;
        limit_except GET {
            deny all;
        }
    }

    # file upload test
    location /upload {
        root www/upload;
        upload_store uploads;
        client_max_body_size 5m;
        limit_except POST GET {
            deny all;
        }
    }

    # delete test
    location /files {
        root www/static;
        limit_except GET DELETE {
            deny all;
        }
    }

    # redirect test
    location /redirect {
        return 301 http://localhost:8080/;
    }

    # permanent redirect
    location /old-page {
        return 301 http://localhost:8080/index.html;
    }

    # error pages test
    location /errors {
        root www;
        autoindex off;
        limit_except GET {
            deny all;
        }
    }
}
