server {
    listen 8080;
    server_name site-one.local;
    client_max_body_size 1m;

    location / {
        root www/static;
        index index.html;
        autoindex off;
        limit_except GET {
            deny all;
        }
    }

    location /images {
        root www;
        autoindex on;
        limit_except GET {
            deny all;
        }
    }
}

server {
    listen 9090;
    server_name site-two.local;
    client_max_body_size 5m;
    error_page 404 /errors/404.html;

    location / {
        root www/api;
        index api.html;
        autoindex on;
        limit_except GET POST {
            deny all;
        }
    }

    location /upload {
        root www/upload;
        upload_store uploads;
        limit_except POST {
            deny all;
        }
    }

    location /errors {
        root www;
        limit_except GET {
            deny all;
        }
    }
}
