server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10G;

    # Basic endpoint
    location / {
        root ./www;
        index index.html;
        limit_except GET {
            deny all;
        }
    }

    # Upload endpoint (For 201 Created and 204 No Content via DELETE)
    location /upload {
        root ./www/upload;
        upload_store ./www/upload;
        limit_except GET POST DELETE {
            deny all;
        }
    }

    # Broken upload endpoint (For 500 Internal Server Error)
    location /bad_upload {
        root ./www;
        upload_store /directory_that_does_not_exist_at_all;
        limit_except POST {
            deny all;
        }
    }

    # Small body size endpoint (For 413 Content Too Large)
    location /small {
        root ./www;
        client_max_body_size 5;
        limit_except POST {
            deny all;
        }
    }

    # Autoindex off (For 403 Forbidden)
    location /forbidden {
        root ./www/forbidden;
        autoindex off;
        limit_except GET {
            deny all;
        }
    }

    # Redirection (For 301 Moved Permanently)
    location /redirect {
        return 301 http://google.com;
    }

    # CGI endpoint (For 504 Gateway Timeout)
    location /cgi {
        root ./www/cgi;
        cgi_pass .py /usr/bin/python3;
        limit_except GET POST {
            deny all;
        }
    }
}
