server {
    listen 0.0.0.0:8080;
    server_name site1.com www.site1.com;
    root www/site1;
    index index.html;
    location / { autoindex off; }
}

server {
    listen 0.0.0.0:8080;
    server_name site2.com www.site2.com;
    root www/site2;
    index index.html;
    location / { autoindex off; }
}

server {
    listen 0.0.0.0:9090;
    server_name site3.com;
    root www/site3;
    index index.html;
    location / { autoindex on; }
}
