server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10M;

    # Serve normal files from /www
    location / {
        root ./www;
        index index.html;
        autoindex on;
    }

    # CGI Location
    location /cgi-bin {
        root ./www/cgi-bin;
        
        # Allow both GET and POST
        limit_except GET POST {
            deny all;
        }

        # Tell webserv to use Python 3 for .py files
        cgi_pass .py /usr/bin/python3;
    }
}
